server:
  bind_addr: 0.0.0.0
  port: 4000
  configs:
    maxconn: 10000
    transfer_buffer_bytes: 4096
    socket_queue_depth_bytes: 8192
    reuse_address: true
    thread_count: 8
  logs:
    log_file: logs
    log_level: info
    rotate_bytes: 1048576
    rotate_duration: 24h
    max_files: 10

backend:
  strategy: roundrobin
  default_port: 8000
  members:
    - 0.0.0.0
    - 0.0.0.0:8001
    - 0.0.0.0:8002


